import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,today,shiftDate,monthEnd,daysBetween,expected,balance,validate,startCycle,checkIn,undoCheckIn,finishCycle,redeem} from '../dist/model.js';
function setup(){const s=initialState();const c=startCycle(s,s.templates[0].id,today(),shiftDate(today(),6));return{s,c}}
test('full lifecycle: snapshot, points, reward, archive and restart',()=>{const{s,c}=setup();s.templates[0].points=30;s.templates[0].name='新版';assert.equal(c.snapshot.points,10);assert.equal(c.snapshot.name,'轻断食');checkIn(s,c.id);s.rewards[0].cost=5;const r=redeem(s,s.rewards[0].id);s.rewards[0].cost=500;s.rewards[0].name='新版奖励';assert.equal(r.cost,5);assert.equal(r.name,'买一本书');assert.equal(balance(s),5);finishCycle(s,c.id,'ended');const next=startCycle(s,s.templates[0].id,today(),shiftDate(today(),3));assert.equal(next.snapshot.points,30);assert.equal(s.checkins.length,1);assert.equal(s.cycles.length,2);validate(s)});
test('duplicate check-ins and concurrent active cycles cannot mint points',()=>{const{s,c}=setup();checkIn(s,c.id);assert.throws(()=>checkIn(s,c.id));assert.throws(()=>startCycle(s,c.templateId,today(),today()));assert.equal(balance(s),10);assert.equal(s.checkins.length,1)});
test('undo cannot make spent balance negative',()=>{const{s,c}=setup();checkIn(s,c.id);s.rewards[0].cost=10;redeem(s,s.rewards[0].id);assert.throws(()=>undoCheckIn(s,c.id));assert.equal(balance(s),0);assert.equal(s.checkins.length,1)});
test('undo restores balance and allows one replacement check-in',()=>{const{s,c}=setup();checkIn(s,c.id);undoCheckIn(s,c.id);assert.equal(balance(s),0);checkIn(s,c.id);assert.equal(balance(s),10)});
test('early completion rejected; ending preserves original denominator',()=>{const{s,c}=setup();assert.throws(()=>finishCycle(s,c.id,'completed'));checkIn(s,c.id);finishCycle(s,c.id,'ended');assert.equal(expected(c),7);assert.equal(balance(s),10);assert.throws(()=>checkIn(s,c.id));assert.throws(()=>undoCheckIn(s,c.id))});
test('completion at end date and archive are separate from template',()=>{const s=initialState(),c=startCycle(s,s.templates[0].id,today(),today());checkIn(s,c.id);finishCycle(s,c.id,'completed');assert.equal(c.status,'completed');assert.equal(s.templates.length,3);assert.equal(c.endedAt,today());validate(s)});
test('weekly plans, future starts, and no scheduled days',()=>{const s=initialState();const dow=new Date(`${today()}T12:00:00`).getDay();s.templates[0].days=[(dow+1)%7];assert.throws(()=>startCycle(s,s.templates[0].id,today(),today()));const c=startCycle(s,s.templates[0].id,shiftDate(today(),1),shiftDate(today(),7));assert.equal(expected(c),1);assert.throws(()=>checkIn(s,c.id));assert.throws(()=>finishCycle(s,c.id,'ended'))});
test('calendar math handles leap days and DST independently',()=>{assert.equal(monthEnd('2028-01-31',1),'2028-02-28');assert.equal(monthEnd('2026-09-21',4),'2027-01-20');assert.equal(daysBetween('2026-11-02','2026-10-31'),2);assert.equal(shiftDate('2028-02-28',1),'2028-02-29')});
test('backup roundtrip preserves complete state',()=>{const{s,c}=setup();checkIn(s,c.id);assert.deepEqual(validate(JSON.parse(JSON.stringify(s))),s)});
test('invalid and inconsistent imports rejected',()=>{const{s,c}=setup();checkIn(s,c.id);const mutate=fn=>{const copy=structuredClone(s);fn(copy);assert.throws(()=>validate(copy))};mutate(x=>x.schemaVersion=999);mutate(x=>x.templates[0].id='bad" onclick="x');mutate(x=>x.cycles[0].startDate='2026-02-30');mutate(x=>x.checkins[0].points=500);mutate(x=>x.checkins.push({...x.checkins[0],id:'different'}));mutate(x=>x.cycles[0].templateId='missing');mutate(x=>x.templates[0].days=[]);mutate(x=>x.redemptions.push({id:'r',rewardId:x.rewards[0].id,name:'reward',cost:900,redeemedAt:new Date().toISOString()}));mutate(x=>x.templates[0].name='<script>'.repeat(20))});
test('disabled templates and rewards cannot be used',()=>{const s=initialState();s.templates[0].archived=true;assert.throws(()=>startCycle(s,s.templates[0].id,today(),today()));s.rewards[0].archived=true;assert.throws(()=>redeem(s,s.rewards[0].id))});
test('overspending does not create a redemption',()=>{const{s,c}=setup();checkIn(s,c.id);assert.throws(()=>redeem(s,s.rewards[0].id));assert.equal(s.redemptions.length,0);assert.equal(balance(s),10)});
